<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.0.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Touchstone.XunitAdapter" Version="0.1.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Test.Shared\Test.Shared.csproj" />
	</ItemGroup>

</Project>
